"""PromptLog modeli eklendi

Revision ID: 6e26690632ba
Revises: 7c16c895bedb
Create Date: 2026-05-30 15:15:41.777073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e26690632ba'
down_revision = '7c16c895bedb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('optimized_prompt', sa.Text(), nullable=False),
    sa.Column('required_files_json', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_logs_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_logs_project_id'))

    op.drop_table('prompt_logs')
    # ### end Alembic commands ###
